format_version: 3
pipelines:
  up42:
    group: first
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: test-repo
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - up42_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          up42_job:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
